const card = [
  {
    data: {
      areaName: "Madhyamgram",
      avgRating: 4.7,
      cloudinaryImageId: "e0hlhbckx9m21a2wllfh",
      costForTwo: "₹150 for two",
      cuisines: ["Ice Cream", " Desserts"],
      id: "335339",
      isOpen: true,
      locality: "Madhyagram",
      name: "Natural Ice Cream",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 7,
        serviceability: "SERVICEABLE",
        slaString: "33 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Madhyamgram",
      avgRating: 4.5,
      cloudinaryImageId: "5220cf2d5049dd54b0fb98bbb3d5a652",
      costForTwo: "₹200 for two",
      cuisines: ["Ice Cream", "Desserts"],
      id: "439822",
      isOpen: true,
      locality: "Sodepur Road",
      name: "Keventers Ice Cream",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 7,
        serviceability: "SERVICEABLE",
        slaString: "33 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Madhyamgram",
      avgRating: 4.5,
      cloudinaryImageId: "txwbgy9vjd2xbjxavibs",
      costForTwo: "₹200 for two",
      cuisines: ["Ice Cream", "Desserts"],
      id: "431847",
      isOpen: true,
      locality: "Sodepur Road",
      name: "Baskin Robbins",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 7,
        serviceability: "SERVICEABLE",
        slaString: "33 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 3.4,
      cloudinaryImageId: "mb1zuzrrgzlplqlbt8rk",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "180362",
      isOpen: true,
      locality: "Sodepur Road",
      name: "Chowman",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.1,
      cloudinaryImageId: "czbxfaw9t1k4l1rornaj",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "225299",
      isOpen: true,
      locality: "Sodepur Road",
      name: "Wow! Momo",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.6,
      cloudinaryImageId: "cbkqr2fll2ox2yj6bony",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "91271",
      isOpen: true,
      locality: "Sodepur Road",
      name: "Baisakhi Restaurant",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.4,
      cloudinaryImageId: "ptcziwuelnlpismwxqlx",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "91744",
      isOpen: true,
      locality: "Sodepur Road",
      name: "Annapurna Khabar Ghar",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 3.8,
      cloudinaryImageId: "vzjl79puj0nxipklsrrp",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "565402",
      isOpen: true,
      locality: "Belghoria",
      name: "BYANJON",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 3.8,
      cloudinaryImageId: "gy8nv6gdvcudynuq3770",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "317478",
      isOpen: true,
      locality: "Belghoria",
      name: "IPSITAS BAKERY",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.0,
      cloudinaryImageId: "m7kwoxxk1d2t62c28qmh",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "496485",
      isOpen: true,
      locality: "Belghoria",
      name: "Srabani'r Tero Parbon",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.2,
      cloudinaryImageId: "z9pot506xzd7sxswasdv",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "394054",
      isOpen: true,
      locality: "Belghoria",
      name: "HOT and SWEET",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 3.5,
      cloudinaryImageId: "ec870ce759ffdb06c6c03a25136108b7",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "150076",
      isOpen: true,
      locality: "Belghoria",
      name: "Fryde Cafe",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.5,
      cloudinaryImageId: "azdsmpleswzfgan4coim",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "356337",
      isOpen: true,
      locality: "Belghoria",
      name: "MEGHDOOT FOOD SERVICE",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
  {
    data: {
      areaName: "Sodepur",
      avgRating: 4.2,
      cloudinaryImageId: "d09e6cd04a575865814385db6f5fc5d8",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Thai", "Seafood", "Beverages", "Desserts"],
      id: "683715",
      isOpen: true,
      locality: "Belghoria",
      name: "Snackopedia",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
      veg: true,
    },
  },
];
export default card;
